name: vashon_s_application16
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  outline_gradient_button: ^2.0.0+1
  intl: ^0.17.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayExtraBold.ttf
          weight: 800
    - family: Share Tech Mono
      fonts: 
        - asset: assets/fonts/ShareTechMonoRegular.ttf
          weight: 400
    - family: Gilroy
      fonts: 
        - asset: assets/fonts/GilroyBlackItalic.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
